// Auto-generated by scripts/generate-graph-json.mjs
// Do not edit manually
import type { Graph } from "./schema";

export const GRAPH_DATA: Graph = {
  "phases": [
    {
      "id": "phase-1-dashboard-diagnosis",
      "label": "Dashboard Diagnosis",
      "phaseNumber": 1,
      "entryAssumption": "I know what my life looks like.",
      "proofMove": "Before insight can land, you must see your current operating system clearly.",
      "replacementModel": "The dashboard is not the territory, but it is the honest starting point.",
      "practiceMove": "Log one week of actual behavior. No interpretation, no judgment.",
      "successMarker": "You can describe your patterns without defensiveness.",
      "failureMode": "Staying in abstract analysis without committing to data.",
      "nextPhaseLogic": "Once you see the dashboard, you must question its physical foundations.",
      "evidenceTier": "practice_validated",
      "pathFunction": [
        "deconstructs",
        "grounds"
      ],
      "stream": "Foundation",
      "summary": "The entry point. Honest self-survey of current patterns, habits, and assumptions before any transformation work."
    },
    {
      "id": "phase-2-physical-desolidification",
      "label": "Physical De-solidification",
      "phaseNumber": 2,
      "entryAssumption": "Matter is solid, dead, and fundamental.",
      "proofMove": "Physics, neuroscience, and phenomenology show that what we call matter is process all the way down.",
      "replacementModel": "Reality is relational process, not dead substance.",
      "practiceMove": "Examine one experience closely: find the boundary between perception and thing.",
      "successMarker": "You no longer take matter for granted as the unquestioned ground.",
      "failureMode": "Intellectualizing without embodying the shift.",
      "nextPhaseLogic": "If matter is process, then mind is not a computer running on meat.",
      "evidenceTier": "established",
      "pathFunction": [
        "deconstructs",
        "grounds"
      ],
      "stream": "Physical / Metaphysical Structure",
      "summary": "Break the assumption that matter is dead, solid, and fundamental. Physics, process philosophy, and phenomenology converge on reality as relational process."
    },
    {
      "id": "phase-3-mind-as-computer-critique",
      "label": "Mind-as-Computer Critique",
      "phaseNumber": 3,
      "entryAssumption": "Mind is a biological computer processing information.",
      "proofMove": "Computational models are useful tools, not ontological truths. Mind is situated, embodied, and enactive.",
      "replacementModel": "Mind is active rendering, not passive computation.",
      "practiceMove": "Notice how thinking changes body state, and body state changes thinking.",
      "successMarker": "You stop treating cognition as abstract information processing.",
      "failureMode": "Replacing one reductive model with another.",
      "nextPhaseLogic": "If mind is not a computer, who or what is running the show?",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "deconstructs"
      ],
      "stream": "Mind / Cognition",
      "summary": "Critique the computational model of mind. Mind is not a CPU; it is situated, embodied, and world-enacting."
    },
    {
      "id": "phase-4-nested-agency",
      "label": "Nested Agency",
      "phaseNumber": 4,
      "entryAssumption": "There is one conscious 'I' in charge.",
      "proofMove": "Agency is layered: unconscious, autonomic, subconscious, reflective, intersubjective.",
      "replacementModel": "Agency is a nested federation, not a unitary command center.",
      "practiceMove": "Observe competing impulses. Which 'I' acts? Note the shift between them.",
      "successMarker": "You notice the multiplicity of self without fragmentation.",
      "failureMode": "Dissociation or infinite regress of who watches the watcher.",
      "nextPhaseLogic": "If agency is nested, what mechanizes or compels those agents?",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "deconstructs",
        "opens_imaginal"
      ],
      "stream": "Agency / Self",
      "summary": "You are not one. Agency is a nested federation of subagents, not a unitary commander."
    },
    {
      "id": "phase-5-mechanicality",
      "label": "Mechanicality",
      "phaseNumber": 5,
      "entryAssumption": "I am freely choosing my actions.",
      "proofMove": "Pattern analysis reveals habit, conditioning, and unconscious programming.",
      "replacementModel": "Much of behavior is mechanical. Freedom is a capacity, not a given.",
      "practiceMove": "Track one automatic reaction per day. What triggered it? What was the script?",
      "successMarker": "You see your conditioning without shame or denial.",
      "failureMode": "Fatalism or nihilism ('I'm just a machine').",
      "nextPhaseLogic": "If behavior is mechanical, what is the mechanism? Dependent arising.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "deconstructs"
      ],
      "stream": "Freedom / Conditioning",
      "summary": "Recognize mechanicality: the vast majority of behavior runs on habit and conditioning, not free choice."
    },
    {
      "id": "phase-6-dependent-arising",
      "label": "Dependent Arising Protocol",
      "phaseNumber": 6,
      "entryAssumption": "Things arise from themselves or from nothing.",
      "proofMove": "Everything arises in dependence on causes and conditions. This includes self, world, and experience.",
      "replacementModel": "Experience is a dependently arisen process, not a collection of fixed things.",
      "practiceMove": "Contact → Feeling → Sign → Proliferation. Trace one experience back through these stages.",
      "successMarker": "You directly see how experience is constructed, not given.",
      "failureMode": "Turning dependent arising into a dry intellectual formula.",
      "nextPhaseLogic": "If everything is dependently arisen, nothing has fixed essence. Emptiness.",
      "evidenceTier": "practice_validated",
      "pathFunction": [
        "deconstructs",
        "grounds"
      ],
      "stream": "Conditionality / Process",
      "summary": "Dependent arising: experience arises through contact → feeling → sign → proliferation. Nothing arises from nothing."
    },
    {
      "id": "phase-7-emptiness",
      "label": "Emptiness / Anti-Reification",
      "phaseNumber": 7,
      "entryAssumption": "Things have fixed, independent essence.",
      "proofMove": "If something has fixed essence, it cannot change. But everything changes. Essence is a useful convention, not a found property.",
      "replacementModel": "Emptiness: things are empty of fixed essence, full of relational process.",
      "practiceMove": "Take one reified concept (self, world, god, soul). Hold it lightly. Investigate its edges.",
      "successMarker": "Reification loosens. You can use concepts without being possessed by them.",
      "failureMode": "Nihilism or flattening ('nothing exists').",
      "nextPhaseLogic": "Emptiness is not the end. It clears ground for non-fabrication.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "deconstructs",
        "corrects_risk"
      ],
      "stream": "Emptiness / Anti-Reification",
      "summary": "Things are empty of fixed essence. Anti-reification: use concepts without being possessed by them."
    },
    {
      "id": "phase-8-non-fabrication",
      "label": "Non-Fabrication / Dzogchen-Mahāmudrā",
      "phaseNumber": 8,
      "entryAssumption": "I must fabricate, construct, or achieve realization.",
      "proofMove": "Rigpa / basic awareness is already present. Fabrication obscures what is already the case.",
      "replacementModel": "Non-fabrication: allow awareness to recognize itself without intervention.",
      "practiceMove": "Short moments, many times. Rest in non-meditation. No fixing, no improving.",
      "successMarker": "Awareness recognizes itself without effort.",
      "failureMode": "Spiritual bypass ('I'm already enlightened, no practice needed') or quietism.",
      "nextPhaseLogic": "Non-fabrication opens into language and sign as creative expression.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "reconstructs",
        "stabilizes"
      ],
      "stream": "Non-Fabrication / Recognition",
      "summary": "Basic awareness is already present. Non-fabrication: rest in recognition without effort or improvement."
    },
    {
      "id": "phase-9-language-sign-mantra",
      "label": "Language / Sign / Mantra",
      "phaseNumber": 9,
      "entryAssumption": "Language describes a pre-existing world.",
      "proofMove": "Language does not just describe; it shapes, renders, and constitutes experience.",
      "replacementModel": "Language / sign / mantra is a technology of world-rendering.",
      "practiceMove": "Use mantra, recitation, or naming practice. Notice how sound and sign shape awareness.",
      "successMarker": "You experience language as creative, not merely referential.",
      "failureMode": "Esoteric inflation (mantra as magic power without grounding).",
      "nextPhaseLogic": "If language renders worlds, what worlds do we want to render? Imaginal reconstruction.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "bridges",
        "reconstructs"
      ],
      "stream": "Language / Sign / Mantra",
      "summary": "Language is not just descriptive; it shapes and renders experience. Mantra as technology of world-rendering."
    },
    {
      "id": "phase-10-imaginal-reconstruction",
      "label": "Imaginal Reconstruction",
      "phaseNumber": 10,
      "entryAssumption": "Imagination is fantasy, not real.",
      "proofMove": "The imaginal is an autonomous ontological domain (Corbin). Symbols, archetypes, and images have their own logic and reality.",
      "replacementModel": "Imagination is a faculty of perception, not a faculty of fiction.",
      "practiceMove": "Engage one symbol actively. Let it speak. Journal its transformations.",
      "successMarker": "You distinguish the imaginal from both fantasy and literal fact.",
      "failureMode": "Inflated identification with archetypes or dissociation from body.",
      "nextPhaseLogic": "Imaginal work must be embodied. Body-energy interface.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "opens_imaginal",
        "reconstructs"
      ],
      "stream": "Imaginal / Symbolic",
      "summary": "The imaginal is an autonomous ontological domain. Active imagination as perception."
    },
    {
      "id": "phase-11-body-energy",
      "label": "Body-Energy Interface",
      "phaseNumber": 11,
      "entryAssumption": "Body is a machine. Energy is metaphorical.",
      "proofMove": "Somatic practices, subtle body traditions, and energy psychology all demonstrate a lived interface between body and awareness.",
      "replacementModel": "Body is the anchor of presence. Energy/feeling is navigable.",
      "practiceMove": "Body scan. Energy tracking. Grounding. Feeling tone labeling.",
      "successMarker": "You can stay present through body sensation without dissociating or fixating.",
      "failureMode": "Energy chasing, somatic bypass, or superstitious internal perceptions.",
      "nextPhaseLogic": "Body-anchored presence enables ritual re-rendering.",
      "evidenceTier": "practice_validated",
      "pathFunction": [
        "grounds",
        "stabilizes"
      ],
      "stream": "Body / Energy / Somatic",
      "summary": "Body as anchor of presence. Subtle body, energy tracking, and grounding as lived realities."
    },
    {
      "id": "phase-12-ritual-re-rendering",
      "label": "Ritual Re-Rendering",
      "phaseNumber": 12,
      "entryAssumption": "Ritual is superstition or mere symbolism.",
      "proofMove": "Ritual reorders body, speech, mind, space, and time. It is a technology of transformation.",
      "replacementModel": "Ritual is a meaning-making and reality-structuring technology.",
      "practiceMove": "Design one small ritual. Perform it with full presence. Note the shift.",
      "successMarker": "You experience ritual as effective without demanding literalist metaphysics.",
      "failureMode": "Ritual inflation (magic without ethics) or mechanical repetition without presence.",
      "nextPhaseLogic": "Ritual opens channels. What speaks through them? Daimon / guidance.",
      "evidenceTier": "historical_ritual",
      "pathFunction": [
        "reconstructs",
        "orders_field"
      ],
      "stream": "Ritual / Practice",
      "summary": "Ritual as technology of transformation. Reorders body, speech, mind, space, and time."
    },
    {
      "id": "phase-13-daimon-guidance",
      "label": "Daimon / Guidance / Vocation",
      "phaseNumber": 13,
      "entryAssumption": "Guidance comes from outside or is pure projection.",
      "proofMove": "Daimonic guidance (Socrates, Jung, Hillman, Corbin) suggests an autonomous inner-other with genuine intelligence.",
      "replacementModel": "The daimon is an autonomous psychic factor that can be consulted without idolatry.",
      "practiceMove": "Active imagination with a guidance figure. Write what comes. Test the fruit.",
      "successMarker": "You can receive guidance without dependency, inflation, or possession.",
      "failureMode": "Daimon inflation (specialness), channeling dependency, or paranoid projection.",
      "nextPhaseLogic": "Daimonic guidance opens into nonordinary states.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "receives_guidance",
        "opens_imaginal"
      ],
      "stream": "Daimon / Guidance / Vocation",
      "summary": "The daimon as autonomous inner-other. Guidance that can be consulted without idolatry or dependency."
    },
    {
      "id": "phase-14-nonordinary-rendering",
      "label": "Nonordinary Rendering",
      "phaseNumber": 14,
      "entryAssumption": "Ordinary waking consciousness is the most reliable state.",
      "proofMove": "Nonordinary states (hypnagogic, meditative, psychedelic, dreaming) reveal different renderings of experience.",
      "replacementModel": "Consciousness can be rendered in multiple modes. Ordinary waking is one mode, not the only mode.",
      "practiceMove": "Explore one nonordinary mode safely: hypnagogic, lucid dream, breathwork, or meditative access.",
      "successMarker": "You can navigate nonordinary states without destabilization or addiction.",
      "failureMode": "State chasing, destabilization, spiritual emergency, or escapism.",
      "nextPhaseLogic": "Nonordinary experience reveals more-than-human reality. Ecology / animism.",
      "evidenceTier": "practice_validated",
      "pathFunction": [
        "opens_imaginal",
        "bridges"
      ],
      "stream": "Nonordinary States",
      "summary": "Consciousness renders in multiple modes. Nonordinary states are valid ways of knowing."
    },
    {
      "id": "phase-15-ecology-animism",
      "label": "Ecology / Animism / More-than-Human",
      "phaseNumber": 15,
      "entryAssumption": "The world is a resource for human use.",
      "proofMove": "Indigenous, animist, and ecological worldviews show that the more-than-human world is communicative and ensouled.",
      "replacementModel": "The world is a community of subjects, not a collection of objects.",
      "practiceMove": "Spend time with one non-human being (tree, animal, place). Listen without agenda.",
      "successMarker": "You experience the world as alive and communicative.",
      "failureMode": "Romantic regression, nature-bypass, or projection onto nature.",
      "nextPhaseLogic": "Animist sensitivity opens into full visionary cosmology.",
      "evidenceTier": "serious_interpretive",
      "pathFunction": [
        "incarnates",
        "bridges"
      ],
      "stream": "Ecology / Animism / More-than-Human",
      "summary": "The world is a community of subjects. Ecological and animist worldviews as genuine ontological proposals."
    },
    {
      "id": "phase-16-visionary-cosmologies",
      "label": "Visionary Cosmologies",
      "phaseNumber": 16,
      "entryAssumption": "The cosmos is dead matter + physical laws.",
      "proofMove": "Visionary cosmologies (Kabbalah, Steiner, Campbell, Gnostic, channeling) offer meaning-rich maps of reality.",
      "replacementModel": "Visionary cosmologies are imaginal maps that may disclose real structures.",
      "practiceMove": "Study one cosmology. Use it as a lens for one week. Note what it reveals and what it obscures.",
      "successMarker": "You can use cosmologies as useful maps without mistaking them for literal territory.",
      "failureMode": "Cosmic map addiction, gnostic inflation, spiritual specialness.",
      "nextPhaseLogic": "Vision must be grounded in social incarnation.",
      "evidenceTier": "visionary_mythic",
      "pathFunction": [
        "opens_imaginal",
        "orders_field"
      ],
      "stream": "Visionary Cosmologies",
      "summary": "Visionary cosmologies as meaning-rich maps. Use them as lenses, not literal territory."
    },
    {
      "id": "phase-17-social-incarnation",
      "label": "Social Incarnation / Praxis",
      "phaseNumber": 17,
      "entryAssumption": "My practice is personal and private.",
      "proofMove": "Practice that does not incarnate in relationship, work, and community is incomplete.",
      "replacementModel": "Practice must be tested, embodied, and expressed in concrete social life.",
      "practiceMove": "Take one insight and embody it in one real relationship or work context this week.",
      "successMarker": "Your practice is visible in how you treat others and do your work.",
      "failureMode": "Social bypass (private enlightenment without relational transformation).",
      "nextPhaseLogic": "Incarnation completes the cycle. The next loop begins at diagnosis.",
      "evidenceTier": "practice_validated",
      "pathFunction": [
        "incarnates",
        "pressure_tests"
      ],
      "stream": "Social / Ethical / Practical",
      "summary": "Practice must incarnate in relationship, work, and community. The cycle completes and renews."
    }
  ],
  "assumptions": [],
  "risks": [
    {
      "id": "risk-occult-inflation",
      "label": "Occult Inflation",
      "statement": "Occult knowledge or practice leads to an inflated sense of specialness, power, or access to hidden truth.",
      "causedBy": [
        "gnostic_impulse",
        "special_knowledge_acquisition"
      ],
      "correctives": [
        "corrective-madhyamaka",
        "corrective-jung-shadow",
        "corrective-humility",
        "corrective-social-praxis"
      ]
    },
    {
      "id": "risk-dry-deconstruction",
      "label": "Dry Deconstruction",
      "statement": "Analysis and deconstruction become an end in themselves, leading to intellectual aridity without transformation.",
      "causedBy": [
        "excessive_analysis",
        "fear_of_practice"
      ],
      "correctives": [
        "corrective-burbea-soulmaking",
        "corrective-rasa",
        "corrective-devotion",
        "corrective-body-practice"
      ]
    },
    {
      "id": "risk-spiritual-bypass",
      "label": "Spiritual Bypass",
      "statement": "Spiritual concepts or practices are used to avoid psychological wounds, social responsibility, or concrete life tasks.",
      "causedBy": [
        "avoidance_of_pain",
        "spiritual_identity"
      ],
      "correctives": [
        "corrective-marx",
        "corrective-somatics",
        "corrective-trauma-work",
        "corrective-concrete-repair"
      ]
    },
    {
      "id": "risk-system-possession",
      "label": "System Possession",
      "statement": "A metaphysical or philosophical system becomes a totalizing lens that resists questioning and distorts experience.",
      "causedBy": [
        "intellectual_map_addiction",
        "certainty_seeking"
      ],
      "correctives": [
        "corrective-krishnamurti",
        "corrective-nagarjuna",
        "corrective-wittgenstein",
        "corrective-fruit-test"
      ]
    },
    {
      "id": "risk-channeling-dependency",
      "label": "Channeling Dependency",
      "statement": "External guidance (entities, spirits, intuitions) replaces personal discernment and decision-making.",
      "causedBy": [
        "fear_of_agency",
        "external_authority_seeking"
      ],
      "correctives": [
        "corrective-nyaya-pramana",
        "corrective-jung-projection",
        "corrective-decision-journal"
      ]
    },
    {
      "id": "risk-energy-chasing",
      "label": "Energy Chasing",
      "statement": "Subtle energy practices become a pursuit of special sensations rather than grounded transformation.",
      "causedBy": [
        "sensation_seeking",
        "body_dissociation"
      ],
      "correctives": [
        "corrective-ethics",
        "corrective-grounding",
        "corrective-madhyamaka"
      ]
    },
    {
      "id": "risk-nihilism",
      "label": "Nihilism",
      "statement": "Emptiness or deconstruction leads to meaninglessness, passivity, or moral nihilism.",
      "causedBy": [
        "misapplied_emptiness",
        "deconstruction_without_reconstruction"
      ],
      "correctives": [
        "corrective-burbea-soulmaking",
        "corrective-social-praxis",
        "corrective-ethics"
      ]
    },
    {
      "id": "risk-intellectual-map-addiction",
      "label": "Intellectual Map Addiction",
      "statement": "Reading, studying, and map-collecting substitutes for actual practice and embodied transformation.",
      "causedBy": [
        "fear_of_practice",
        "desire_for_certainty"
      ],
      "correctives": [
        "corrective-nanananda-protocol",
        "corrective-body-grounding",
        "corrective-social-praxis",
        "corrective-source-fasting"
      ]
    },
    {
      "id": "risk-cosmic-specialness",
      "label": "Cosmic Specialness",
      "statement": "Believing one has unique cosmic knowledge, mission, or status based on visionary or channeled material.",
      "causedBy": [
        "gnostic_impulse",
        "visionary_experience_without_grounding"
      ],
      "correctives": [
        "corrective-humility",
        "corrective-fruit-test",
        "corrective-social-praxis",
        "corrective-madhyamaka"
      ]
    },
    {
      "id": "risk-category-error",
      "label": "Category Error",
      "statement": "Mistaking conceptual parallels for historical influence, or one domain's conclusions for another domain's proof.",
      "causedBy": [
        "lack_of_historical_distinction",
        "domain_collapse"
      ],
      "correctives": [
        "corrective-epistemic-tiering",
        "corrective-historical-distinction",
        "corrective-madhyamaka"
      ]
    },
    {
      "id": "risk-attention-collapse",
      "label": "Attention Collapse",
      "statement": "Practice or nonordinary exploration leads to fragmented attention, drowsiness, or inability to maintain focus.",
      "causedBy": [
        "overextension",
        "lack_of_grounding",
        "poor_timing"
      ],
      "correctives": [
        "corrective-body-anchor",
        "corrective-shorter-session",
        "corrective-contact-feeling-sign"
      ]
    },
    {
      "id": "risk-state-chasing",
      "label": "State Chasing",
      "statement": "Pursuit of interesting nonordinary states replaces grounded practice and ordinary-life integration.",
      "causedBy": [
        "novelty_seeking",
        "dissatisfaction_with_ordinary"
      ],
      "correctives": [
        "corrective-body-grounding",
        "corrective-ordinary-life-practice",
        "corrective-social-praxis"
      ]
    }
  ],
  "correctives": [
    {
      "id": "corrective-madhyamaka",
      "label": "Madhyamaka / Anti-Reification",
      "statement": "Use Madhyamaka dialectics to deconstruct fixed views without falling into nihilism.",
      "practice": "Apply four-corner negation to any reified concept."
    },
    {
      "id": "corrective-jung-shadow",
      "label": "Jung Shadow Work",
      "statement": "Integrate rejected and unconscious aspects of self through active imagination and dream work.",
      "practice": "Active imagination with shadow figures. Journal without censorship."
    },
    {
      "id": "corrective-humility",
      "label": "Christian / Contemplative Humility",
      "statement": "Cultivate humility through service, confession, and recognition of limited perspective.",
      "practice": "Daily examen. One anonymous service act per week."
    },
    {
      "id": "corrective-social-praxis",
      "label": "Social Praxis",
      "statement": "Ground all insight in concrete relationship, work, and community.",
      "practice": "Take one insight and apply it in a specific relationship or work context."
    },
    {
      "id": "corrective-burbea-soulmaking",
      "label": "Burbea Soulmaking",
      "statement": "Use emptiness to free imagination, not to flatten meaning. Soulmaking as poetic-emergent practice.",
      "practice": "Take one experience and investigate its imaginal dimensions."
    },
    {
      "id": "corrective-rasa",
      "label": "Rasa / Aesthetic Savoring",
      "statement": "Develop taste and aesthetic sensitivity as a mode of spiritual practice.",
      "practice": "Engage one art form with full presence daily."
    },
    {
      "id": "corrective-devotion",
      "label": "Devotion / Bhakti",
      "statement": "Cultivate devotion as a counterbalance to dry deconstruction and inflation.",
      "practice": "Daily devotional practice: prayer, offering, or praise."
    },
    {
      "id": "corrective-body-practice",
      "label": "Body Practice",
      "statement": "Ground through body: yoga, martial arts, somatic therapy, or movement practice.",
      "practice": "30 minutes of body practice daily."
    },
    {
      "id": "corrective-marx",
      "label": "Marx / Ideology Critique",
      "statement": "Examine how spiritual practices may serve material and social interests.",
      "practice": "Analyze one spiritual belief through material conditions."
    },
    {
      "id": "corrective-somatics",
      "label": "Somatics / Trauma Work",
      "statement": "Address psychological wounds through body-based therapeutic approaches.",
      "practice": "Somatic therapy or trauma-informed bodywork."
    },
    {
      "id": "corrective-trauma-work",
      "label": "Trauma Resolution",
      "statement": "Process unresolved trauma before or alongside deep spiritual practice.",
      "practice": "Trauma-informed therapy or peer support."
    },
    {
      "id": "corrective-concrete-repair",
      "label": "Concrete Repair",
      "statement": "Make amends and repair actual relationships and situations.",
      "practice": "Identify one relationship needing repair. Take one step today."
    },
    {
      "id": "corrective-krishnamurti",
      "label": "Krishnamurti / Choiceless Awareness",
      "statement": "Observe without observer. See the system without identifying with it.",
      "practice": "Sit and observe thoughts without labeling them as yours."
    },
    {
      "id": "corrective-nagarjuna",
      "label": "Nāgārjuna / Middle Way",
      "statement": "Avoid eternalism and nihilism through rigorous dialectical analysis.",
      "practice": "Apply catuṣkoṭi to any absolute claim."
    },
    {
      "id": "corrective-wittgenstein",
      "label": "Wittgenstein / Language Games",
      "statement": "Examine how language creates pseudo-problems. Distinguish use from essence.",
      "practice": "Ask 'how is this word used?' rather than 'what does it mean?'"
    },
    {
      "id": "corrective-fruit-test",
      "label": "Fruit Test",
      "statement": "Test any teaching, practice, or experience by its fruits: clarity, kindness, discipline, embodiment, freedom.",
      "practice": "For each teaching, ask: does this produce clarity, kindness, and concrete betterment?"
    },
    {
      "id": "corrective-nyaya-pramana",
      "label": "Nyāya Pramāṇa / Epistemic Discipline",
      "statement": "Use epistemic criteria to evaluate claims: perception, inference, testimony, comparison, and implication.",
      "practice": "Classify each claim by its epistemic source and validity."
    },
    {
      "id": "corrective-jung-projection",
      "label": "Jung Projection Recognition",
      "statement": "Examine how external entities may be projections of unconscious contents.",
      "practice": "Journal about guidance figures. What part of self might they represent?"
    },
    {
      "id": "corrective-decision-journal",
      "label": "Decision Journal",
      "statement": "Track decisions and their outcomes to build discernment and reduce dependency.",
      "practice": "Log one decision per day with rationale and outcome."
    },
    {
      "id": "corrective-nanananda-protocol",
      "label": "Ñāṇananda Contact-Feeling-Sign Protocol",
      "statement": "Trace experience back to contact → feeling → sign → proliferation. See how reification arises.",
      "practice": "Label: contact → pleasant/neutral/unpleasant → sign → story → release."
    },
    {
      "id": "corrective-body-grounding",
      "label": "Body Grounding",
      "statement": "Anchor awareness in physical sensation to prevent dissociation and attention collapse.",
      "practice": "Three grounding breaths before any practice. Feel feet on floor."
    },
    {
      "id": "corrective-source-fasting",
      "label": "Source Fasting",
      "statement": "Take a break from reading, studying, and content consumption to let direct experience lead.",
      "practice": "No cosmology or esoteric reading for one week. Journal what arises."
    },
    {
      "id": "corrective-epistemic-tiering",
      "label": "Epistemic Tiering",
      "statement": "Explicitly distinguish evidence levels: established, interpretive, speculative, visionary, ritual, practice-validated.",
      "practice": "Before making a claim, assign its evidence tier."
    },
    {
      "id": "corrective-historical-distinction",
      "label": "Historical Distinction",
      "statement": "Distinguish conceptual parallels from historical influence. Map lineage carefully.",
      "practice": "Before claiming influence, check: is there an attested historical pathway?"
    },
    {
      "id": "corrective-body-anchor",
      "label": "Body Anchor",
      "statement": "Use a physical anchor (breath, posture, touch) to stabilize attention during nonordinary practice.",
      "practice": "Keep one hand on belly. When attention drifts, return to the breath-hand-belly triangle."
    },
    {
      "id": "corrective-shorter-session",
      "label": "Shorter Session",
      "statement": "Reduce practice duration to prevent fatigue and attention collapse.",
      "practice": "Do 10 minutes instead of 30. Stop while still clear."
    },
    {
      "id": "corrective-contact-feeling-sign",
      "label": "Contact-Feeling-Sign Journal",
      "statement": "After each practice session, log contact → feeling-tone → sign → pull → story.",
      "practice": "Write one line per stage immediately after practice."
    },
    {
      "id": "corrective-ordinary-life-practice",
      "label": "Ordinary Life Practice",
      "statement": "Bring practice into daily activities: walking, eating, conversing, working.",
      "practice": "Choose one daily activity and do it as practice."
    }
  ],
  "warnings": [
    {
      "id": "warning-physics-magic",
      "label": "Physics does not prove magic",
      "statement": "Physics may de-solidify crude matter, but it does not automatically validate ritual or occult claims."
    },
    {
      "id": "warning-godel-soul",
      "label": "Gödel does not prove souls",
      "statement": "Gödel-style arguments challenge some forms of formalism, but do not establish a soul ontology."
    },
    {
      "id": "warning-conceptual-not-historical",
      "label": "Conceptual parallel is not historical influence",
      "statement": "Structural resemblance between systems should not be presented as lineage."
    },
    {
      "id": "warning-channeling-testimony",
      "label": "Channeling is not reliable testimony by default",
      "statement": "Channeling may be imaginally meaningful but should not be treated as automatically factual."
    },
    {
      "id": "warning-nonduality-ethics",
      "label": "Nonduality does not cancel ethics",
      "statement": "Nondual or emptiness language must not be used to skip conduct, compassion, or responsibility."
    },
    {
      "id": "warning-symbol-responsibility",
      "label": "Symbol does not remove responsibility",
      "statement": "Astrology, tarot, dreams, or omens may illuminate patterns but do not remove agency or repair."
    },
    {
      "id": "warning-ritual-power",
      "label": "Ritual power invites inflation",
      "statement": "Ritual can stabilize attention and meaning, but can also feed control fantasy and specialness."
    }
  ],
  "traditions": [
    {
      "id": "tradition-neoplatonism",
      "label": "Neoplatonism",
      "aliases": [
        "Late Antique Platonism"
      ],
      "stream": "Greek Platonism / Neoplatonism",
      "period": "Late Antiquity",
      "geography": [
        "Mediterranean"
      ],
      "definition": "A late antique Platonic tradition centered on the One, Intellect, Soul, emanation, participation, ascent, and return.",
      "coreClaims": [
        "Reality is hierarchically ordered.",
        "Multiplicity proceeds from a higher unity.",
        "The soul can turn back toward its source.",
        "Philosophy and theurgy can participate in higher order."
      ],
      "corePractices": [
        "contemplation",
        "philosophical purification",
        "theurgy in Iamblichean forms"
      ],
      "coreTexts": [
        "Plotinus — Enneads",
        "Iamblichus — On the Mysteries",
        "Proclus — Elements of Theology"
      ],
      "representativeFigures": [
        "Plotinus",
        "Porphyry",
        "Iamblichus",
        "Proclus"
      ],
      "evidenceTier": "serious_interpretive",
      "useFor": [
        "emanation",
        "participation",
        "theurgy",
        "Western esoteric lineage"
      ],
      "doNotUseFor": [
        "proving modern magic",
        "claiming all mysticism is Platonism",
        "collapsing Buddhism or Tantra into Greek metaphysics"
      ],
      "commonCategoryErrors": [
        "Treating conceptual similarity as historical influence.",
        "Flattening Neoplatonic hierarchy into generic nonduality."
      ],
      "risks": [
        "metaphysical system possession",
        "hierarchy inflation"
      ],
      "correctives": [
        "Madhyamaka anti-reification",
        "historical distinction",
        "praxis"
      ],
      "status": "approved"
    },
    {
      "id": "tradition-gnosticism",
      "label": "Gnosticism",
      "aliases": [
        "ancient gnosis",
        "gnostic movements"
      ],
      "stream": "Hermetic / Gnostic / Salvational Cosmology",
      "period": "Late Antiquity",
      "definition": "A family of ancient salvational religious movements centered on gnosis, divine spark, cosmic ignorance, archonic powers, demiurgic creation in some systems, and return to a higher divine source.",
      "coreClaims": [
        "Ordinary worldly existence is bound by ignorance.",
        "Saving knowledge discloses the soul's deeper origin.",
        "Cosmic powers may obstruct liberation.",
        "The visible world is not ultimate."
      ],
      "coreTexts": [
        "Nag Hammadi texts",
        "Gospel of Thomas",
        "Apocryphon of John",
        "Valentinian materials"
      ],
      "evidenceTier": "serious_interpretive",
      "useFor": [
        "salvational cosmology",
        "hidden knowledge structures",
        "ancient archon/demiurge frameworks",
        "comparison with modern UFO/channeling myths only as conceptual parallel"
      ],
      "doNotUseFor": [
        "claiming every hidden-control theory is Gnosticism",
        "equating Galactic Federation directly with ancient Gnosticism",
        "treating modern conspiracy cosmologies as historically Gnostic"
      ],
      "commonCategoryErrors": [
        "Calling any cosmic hierarchy Gnosticism.",
        "Mistaking structural resemblance for direct lineage."
      ],
      "risks": [
        "cosmic paranoia",
        "special knowledge inflation",
        "world-rejection"
      ],
      "correctives": [
        "historical distinction",
        "Madhyamaka",
        "praxis",
        "fruit-test"
      ],
      "status": "approved"
    },
    {
      "id": "tradition-tantra",
      "label": "Tantra",
      "stream": "Sanskrit / Buddhist / Tibetan",
      "definition": "A diverse family of South Asian religious technologies using mantra, deity, subtle body, ritual, initiation, visualization, and transformed identity to reorder body, speech, mind, and cosmos.",
      "coreClaims": [
        "Body, speech, and mind can be ritually transformed.",
        "Sound, image, gesture, and deity-form can function as technologies of realization.",
        "Ordinary identity can be re-rendered through consecrated symbolic embodiment."
      ],
      "corePractices": [
        "mantra",
        "nyāsa",
        "deity yoga",
        "maṇḍala",
        "subtle body practice",
        "ritual offering"
      ],
      "evidenceTier": "historical_ritual",
      "useFor": [
        "body-speech-mind reordering",
        "ritual technology",
        "mantra theory",
        "deity-body reconstruction"
      ],
      "doNotUseFor": [
        "generic energy mysticism",
        "ego inflation",
        "unqualified sexualized interpretations",
        "proof of New Age manifestation claims"
      ],
      "commonCategoryErrors": [
        "Treating all energy work as Tantra.",
        "Treating deity identity as ego empowerment.",
        "Ignoring initiation, ethics, lineage, and context."
      ],
      "risks": [
        "energy chasing",
        "spiritual bypass",
        "inflation",
        "appropriation"
      ],
      "correctives": [
        "ethics",
        "grounding",
        "qualified tradition",
        "Madhyamaka",
        "teacher/context"
      ],
      "status": "approved"
    },
    {
      "id": "tradition-depression-era-buddhism",
      "label": "Theravāda / Early Buddhism",
      "aliases": [
        "Early Buddhism",
        "Pāli Buddhism"
      ],
      "stream": "Buddhist / Early Buddhism",
      "period": "6th–4th century BCE",
      "geography": [
        "India",
        "Sri Lanka",
        "Southeast Asia"
      ],
      "definition": "The earliest surviving Buddhist tradition, centered on the Pāli canon, the four noble truths, dependent origination, and the eightfold path.",
      "coreClaims": [
        "Experience is marked by impermanence, unsatisfactoriness, and non-self.",
        "Craving and ignorance drive rebirth and suffering.",
        "The eightfold path leads to the cessation of suffering.",
        "Liberation is achievable in this life."
      ],
      "corePractices": [
        "mindfulness of body, feeling, mind, and dhammas",
        "sense restraint",
        "meditation (samatha and vipassanā)",
        "ethical conduct"
      ],
      "coreTexts": [
        "Sutta Piṭaka",
        "Vinaya Piṭaka",
        "Abhidhamma Piṭaka"
      ],
      "representativeFigures": [
        "The Buddha (Siddhattha Gotama)",
        "Sāriputta",
        "Mahinda",
        "Buddhaghosa"
      ],
      "evidenceTier": "serious_interpretive",
      "useFor": [
        "dependent arising",
        "emptiness analysis",
        "contact/feeling/sign protocol",
        "anti-reification"
      ],
      "doNotUseFor": [
        "proving that nothing exists",
        "claiming Buddhism is just therapy",
        "skipping ethics"
      ],
      "commonCategoryErrors": [
        "Treating early Buddhism as nihilistic.",
        "Collapsing Mahāyāna and Theravāda."
      ],
      "risks": [
        "dry intellectualism",
        "world-rejection",
        "practice without compassion"
      ],
      "correctives": [
        "compassion practice",
        "body grounding",
        "social engagement"
      ],
      "status": "approved"
    }
  ],
  "sourceCards": [
    {
      "id": "source-nanananda-concept-reality",
      "title": "Concept and Reality",
      "author": "Bhikkhu Ñāṇananda",
      "tradition": "Theravāda / dependent arising analysis",
      "phase": [
        6
      ],
      "sourceType": "book",
      "epistemicTier": "practice_validated",
      "coreContribution": "Analyzes papañca and conceptual proliferation as self/world construction.",
      "breaks": [
        "Self and world are solid realities"
      ],
      "enables": [
        "Contact/Feeling/Sign protocol"
      ],
      "correctives": [
        "Occult literalism",
        "Intellectual map addiction"
      ],
      "bestUsedFor": "Dependent arising, sign, proliferation, anti-reification.",
      "caution": "Can become dry if not balanced by compassion, body, and soulmaking."
    },
    {
      "id": "source-plotinus-enneads",
      "title": "Enneads",
      "author": "Plotinus",
      "tradition": "Neoplatonism",
      "phase": [
        2,
        7
      ],
      "sourceType": "primary_text",
      "epistemicTier": "serious_interpretive",
      "coreContribution": "Foundational text of Neoplatonic philosophy: the One, Intellect, Soul, emanation, and return.",
      "breaks": [
        "Matter is dead and fundamental"
      ],
      "grounds": [
        "Hierarchical reality",
        "Participatory metaphysics"
      ],
      "enables": [
        "Contemplative ascent",
        "Theurgic philosophy"
      ],
      "risks": [
        "Metaphysical system possession",
        "Hierarchy inflation"
      ],
      "correctives": [
        "Madhyamaka",
        "Historical distinction"
      ],
      "bestUsedFor": "Emanation metaphysics, contemplative philosophy, Western esoteric lineage.",
      "caution": "Easy to treat as literal cosmology rather than contemplative map."
    },
    {
      "id": "source-iamblichus-mysteries",
      "title": "On the Mysteries",
      "author": "Iamblichus",
      "tradition": "Neoplatonism / Theurgy",
      "phase": [
        12,
        13
      ],
      "sourceType": "primary_text",
      "epistemicTier": "serious_interpretive",
      "coreContribution": "Defends theurgy as a genuine mode of participation in the divine, against purely philosophical approaches.",
      "breaks": [
        "Ritual is inferior to philosophy"
      ],
      "grounds": [
        "Ritual as genuine participation"
      ],
      "enables": [
        "Ritual re-rendering",
        "Theurgic practice framework"
      ],
      "risks": [
        "Ritual inflation",
        "Supernatural literalism"
      ],
      "correctives": [
        "Epistemic tiering",
        "Fruit test"
      ],
      "bestUsedFor": "Theurgy, ritual philosophy, daimonology.",
      "caution": "Easy to take as literal supernatural claims rather than participatory metaphysics."
    },
    {
      "id": "source-corbin-imaginal",
      "title": "Creative Imagination in the Sufism of Ibn Arabi",
      "author": "Henry Corbin",
      "tradition": "Sufism / Phenomenology / Imaginal",
      "phase": [
        10,
        13
      ],
      "sourceType": "book",
      "epistemicTier": "serious_interpretive",
      "coreContribution": "Develops the concept of the imaginal (mundus imaginalis) as an autonomous ontological domain.",
      "breaks": [
        "Imagination is fantasy"
      ],
      "grounds": [
        "Imagination as perception",
        "Intermediate realm"
      ],
      "enables": [
        "Active imagination",
        "Symbolic engagement",
        "Guidance figures"
      ],
      "risks": [
        "Imaginal inflation",
        "Psychotic confusion"
      ],
      "correctives": [
        "Historical distinction",
        "Fruit test",
        "Body grounding"
      ],
      "bestUsedFor": "Imaginal practice, active imagination, daimon work."
    },
    {
      "id": "source-nagarjuna-mulamadhyamaka",
      "title": "Mūlamadhyamakakārikā",
      "author": "Nāgārjuna",
      "tradition": "Madhyamaka / Mahāyāna Buddhism",
      "phase": [
        7
      ],
      "sourceType": "primary_text",
      "epistemicTier": "serious_interpretive",
      "coreContribution": "Foundational text of the Madhyamaka school. Uses reductio arguments to show all phenomena empty of inherent existence.",
      "breaks": [
        "Things have fixed essence"
      ],
      "grounds": [
        "Emptiness as dependent arising"
      ],
      "enables": [
        "Anti-reification practice",
        "Four-corner negation"
      ],
      "correctives": [
        "Metaphysical system possession",
        "Occult inflation"
      ],
      "bestUsedFor": "Emptiness analysis, anti-reification, deconstruction of fixed views.",
      "caution": "Can be weaponized for nihilism if not balanced by compassion and conventional truth."
    },
    {
      "id": "source-campbell-mbt",
      "title": "The Masks of God / The Hero with a Thousand Faces",
      "author": "Joseph Campbell",
      "tradition": "Comparative Mythology / Perennial Philosophy",
      "phase": [
        14,
        16
      ],
      "sourceType": "book",
      "epistemicTier": "speculative",
      "coreContribution": "Argues that world mythologies share deep structural patterns and that myth serves functions of metaphysical, cosmological, sociological, and pedagogical explanation.",
      "breaks": [
        "Myth is false"
      ],
      "grounds": [
        "Myth as meaningful structure"
      ],
      "enables": [
        "Comparative mythological analysis",
        "Archetypal engagement"
      ],
      "risks": [
        "Perennialist flattening",
        "Universalist overreach"
      ],
      "correctives": [
        "Historical distinction",
        "Cultural specificity",
        "Fruit test"
      ],
      "bestUsedFor": "Comparative mythology, archetypal patterns, narrative metaphysics.",
      "caution": "Campbell's perennialist framework can flatten cultural specificity and historical distinction."
    },
    {
      "id": "source-hoffman-interface",
      "title": "The Case Against Reality",
      "author": "Donald Hoffman",
      "tradition": "Cognitive Science / Evolutionary Psychology",
      "phase": [
        2,
        14
      ],
      "sourceType": "book",
      "epistemicTier": "speculative",
      "coreContribution": "Argues that evolution shapes perception to hide reality, not reveal it. Perception is an interface, not a window.",
      "breaks": [
        "Perception reveals reality as it is"
      ],
      "grounds": [
        "Interface theory of perception"
      ],
      "enables": [
        "Nonordinary rendering exploration",
        "Phenomenological investigation"
      ],
      "risks": [
        "Interface theory as literal metaphysics",
        "Anti-realism"
      ],
      "correctives": [
        "Epistemic tiering",
        "Phenomenological grounding",
        "Fruit test"
      ],
      "bestUsedFor": "Interface theory, perception, nonordinary states as alternative renderings.",
      "caution": "Hoffman's conscious agent model is speculative, not established science."
    },
    {
      "id": "source-burbea-soulmaking",
      "title": "Seeing That Frees",
      "author": "Rob Burbea",
      "tradition": "Buddhist / Hermeneutical / Soulmaking",
      "phase": [
        7,
        10
      ],
      "sourceType": "book",
      "epistemicTier": "practice_validated",
      "coreContribution": "Integrates emptiness practice with imaginal soulmaking: emptiness frees imagination rather than flattening meaning.",
      "breaks": [
        "Emptiness is nihilistic",
        "Imagination is delusion"
      ],
      "grounds": [
        "Emptiness as creative freedom"
      ],
      "enables": [
        "Soulmaking practice",
        "Imaginal-emergent practice"
      ],
      "correctives": [
        "Dry deconstruction",
        "Occult inflation"
      ],
      "bestUsedFor": "Emptiness-imagination integration, soulmaking, poetic practice.",
      "caution": "Requires stable emptiness grounding before imaginal engagement."
    }
  ],
  "edges": [
    {
      "id": "edge-phase-1-to-2",
      "source": "phase-1-dashboard-diagnosis",
      "target": "phase-2-physical-desolidification",
      "kind": "bridges",
      "label": "Dashboard reveals need to question physical foundations"
    },
    {
      "id": "edge-phase-2-to-3",
      "source": "phase-2-physical-desolidification",
      "target": "phase-3-mind-as-computer-critique",
      "kind": "bridges",
      "label": "If matter is process, mind is not a computer"
    },
    {
      "id": "edge-phase-3-to-4",
      "source": "phase-3-mind-as-computer-critique",
      "target": "phase-4-nested-agency",
      "kind": "bridges",
      "label": "If mind is not a computer, who is running the show?"
    },
    {
      "id": "edge-phase-4-to-5",
      "source": "phase-4-nested-agency",
      "target": "phase-5-mechanicality",
      "kind": "bridges",
      "label": "Agency is nested but much of it runs mechanically"
    },
    {
      "id": "edge-phase-5-to-6",
      "source": "phase-5-mechanicality",
      "target": "phase-6-dependent-arising",
      "kind": "bridges",
      "label": "Mechanism is dependent arising"
    },
    {
      "id": "edge-phase-6-to-7",
      "source": "phase-6-dependent-arising",
      "target": "phase-7-emptiness",
      "kind": "bridges",
      "label": "Dependent arising implies emptiness of fixed essence"
    },
    {
      "id": "edge-phase-7-to-8",
      "source": "phase-7-emptiness",
      "target": "phase-8-non-fabrication",
      "kind": "bridges",
      "label": "Emptiness clears ground for non-fabrication"
    },
    {
      "id": "edge-phase-8-to-9",
      "source": "phase-8-non-fabrication",
      "target": "phase-9-language-sign-mantra",
      "kind": "bridges",
      "label": "Non-fabrication opens into creative expression"
    },
    {
      "id": "edge-phase-9-to-10",
      "source": "phase-9-language-sign-mantra",
      "target": "phase-10-imaginal-reconstruction",
      "kind": "bridges",
      "label": "Language renders worlds; imaginal reconstructs them"
    },
    {
      "id": "edge-phase-10-to-11",
      "source": "phase-10-imaginal-reconstruction",
      "target": "phase-11-body-energy",
      "kind": "bridges",
      "label": "Imaginal work must be embodied"
    },
    {
      "id": "edge-phase-11-to-12",
      "source": "phase-11-body-energy",
      "target": "phase-12-ritual-re-rendering",
      "kind": "bridges",
      "label": "Body-anchored presence enables ritual"
    },
    {
      "id": "edge-phase-12-to-13",
      "source": "phase-12-ritual-re-rendering",
      "target": "phase-13-daimon-guidance",
      "kind": "bridges",
      "label": "Ritual opens channels for guidance"
    },
    {
      "id": "edge-phase-13-to-14",
      "source": "phase-13-daimon-guidance",
      "target": "phase-14-nonordinary-rendering",
      "kind": "bridges",
      "label": "Guidance opens into nonordinary states"
    },
    {
      "id": "edge-phase-14-to-15",
      "source": "phase-14-nonordinary-rendering",
      "target": "phase-15-ecology-animism",
      "kind": "bridges",
      "label": "Nonordinary reveals more-than-human reality"
    },
    {
      "id": "edge-phase-15-to-16",
      "source": "phase-15-ecology-animism",
      "target": "phase-16-visionary-cosmologies",
      "kind": "bridges",
      "label": "Animist sensitivity opens into cosmology"
    },
    {
      "id": "edge-phase-16-to-17",
      "source": "phase-16-visionary-cosmologies",
      "target": "phase-17-social-incarnation",
      "kind": "bridges",
      "label": "Vision must be grounded in social life"
    },
    {
      "id": "edge-phase-17-to-1",
      "source": "phase-17-social-incarnation",
      "target": "phase-1-dashboard-diagnosis",
      "kind": "bridges",
      "label": "Cycle renews at next diagnosis"
    },
    {
      "id": "edge-risk-occult-inflation-corrective-madhyamaka",
      "source": "risk-occult-inflation",
      "target": "corrective-madhyamaka",
      "kind": "corrects",
      "label": "Madhyamaka deconstructs inflation"
    },
    {
      "id": "edge-risk-occult-inflation-corrective-jung-shadow",
      "source": "risk-occult-inflation",
      "target": "corrective-jung-shadow",
      "kind": "corrects",
      "label": "Shadow integration deflates specialness"
    },
    {
      "id": "edge-risk-dry-deconstruction-corrective-burbea",
      "source": "risk-dry-deconstruction",
      "target": "corrective-burbea-soulmaking",
      "kind": "corrects",
      "label": "Soulmaking restores meaning"
    },
    {
      "id": "edge-risk-system-possession-corrective-wittgenstein",
      "source": "risk-system-possession",
      "target": "corrective-wittgenstein",
      "kind": "corrects",
      "label": "Language game analysis breaks system trance"
    },
    {
      "id": "edge-risk-category-error-corrective-epistemic-tiering",
      "source": "risk-category-error",
      "target": "corrective-epistemic-tiering",
      "kind": "corrects",
      "label": "Epistemic tiering prevents domain collapse"
    },
    {
      "id": "edge-risk-attention-collapse-corrective-body-anchor",
      "source": "risk-attention-collapse",
      "target": "corrective-body-anchor",
      "kind": "corrects",
      "label": "Body anchor stabilizes attention"
    },
    {
      "id": "edge-risk-attention-collapse-corrective-shorter-session",
      "source": "risk-attention-collapse",
      "target": "corrective-shorter-session",
      "kind": "corrects",
      "label": "Shorter sessions prevent fatigue"
    },
    {
      "id": "edge-warning-physics-magic-corrective-epistemic-tiering",
      "source": "warning-physics-magic",
      "target": "corrective-epistemic-tiering",
      "kind": "corrects",
      "label": "Tier claims to avoid category errors"
    },
    {
      "id": "edge-warning-conceptual-not-historical-corrective-historical-distinction",
      "source": "warning-conceptual-not-historical",
      "target": "corrective-historical-distinction",
      "kind": "corrects",
      "label": "Distinguish parallel from influence"
    },
    {
      "id": "edge-source-nanananda-to-phase-6",
      "source": "source-nanananda-concept-reality",
      "target": "phase-6-dependent-arising",
      "kind": "evidenced_by",
      "label": "Core text for dependent arising protocol"
    },
    {
      "id": "edge-source-plotinus-to-phase-2",
      "source": "source-plotinus-enneads",
      "target": "phase-2-physical-desolidification",
      "kind": "evidenced_by",
      "label": "Challenges dead matter assumption"
    },
    {
      "id": "edge-source-nagarjuna-to-phase-7",
      "source": "source-nagarjuna-mulamadhyamaka",
      "target": "phase-7-emptiness",
      "kind": "evidenced_by",
      "label": "Foundational emptiness text"
    },
    {
      "id": "edge-source-burbea-to-phase-7",
      "source": "source-burbea-soulmaking",
      "target": "phase-7-emptiness",
      "kind": "evidenced_by",
      "label": "Emptiness as creative freedom"
    },
    {
      "id": "edge-source-corbin-to-phase-10",
      "source": "source-corbin-imaginal",
      "target": "phase-10-imaginal-reconstruction",
      "kind": "evidenced_by",
      "label": "Imaginal ontology"
    },
    {
      "id": "edge-source-iamblichus-to-phase-12",
      "source": "source-iamblichus-mysteries",
      "target": "phase-12-ritual-re-rendering",
      "kind": "evidenced_by",
      "label": "Theurgic ritual framework"
    },
    {
      "id": "edge-source-hoffman-to-phase-14",
      "source": "source-hoffman-interface",
      "target": "phase-14-nonordinary-rendering",
      "kind": "evidenced_by",
      "label": "Interface theory supports nonordinary rendering"
    },
    {
      "id": "edge-tradition-neoplatonism-phase-2",
      "source": "tradition-neoplatonism",
      "target": "phase-2-physical-desolidification",
      "kind": "maps_to_phase",
      "label": "Neoplatonic emanation de-solidifies matter"
    },
    {
      "id": "edge-tradition-neoplatonism-phase-12",
      "source": "tradition-neoplatonism",
      "target": "phase-12-ritual-re-rendering",
      "kind": "maps_to_phase",
      "label": "Theurgy as ritual re-rendering"
    },
    {
      "id": "edge-tradition-depression-era-buddhism-phase-6",
      "source": "tradition-depression-era-buddhism",
      "target": "phase-6-dependent-arising",
      "kind": "maps_to_phase",
      "label": "Dependent arising is core early Buddhist teaching"
    },
    {
      "id": "edge-tradition-depression-era-buddhism-phase-7",
      "source": "tradition-depression-era-buddhism",
      "target": "phase-7-emptiness",
      "kind": "maps_to_phase",
      "label": "Emptiness derived from dependent arising"
    },
    {
      "id": "edge-tradition-tantra-phase-12",
      "source": "tradition-tantra",
      "target": "phase-12-ritual-re-rendering",
      "kind": "maps_to_phase",
      "label": "Tantric ritual technology"
    }
  ]
};
